// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/grpcserver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_proto_grpcserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{0}
}

func (x *Link) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shortlink     string                 `protobuf:"bytes,1,opt,name=shortlink,proto3" json:"shortlink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortLink) Reset() {
	*x = ShortLink{}
	mi := &file_proto_grpcserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortLink) ProtoMessage() {}

func (x *ShortLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortLink.ProtoReflect.Descriptor instead.
func (*ShortLink) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{1}
}

func (x *ShortLink) GetShortlink() string {
	if x != nil {
		return x.Shortlink
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_proto_grpcserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{2}
}

func (x *Status) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type PingDBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingDBRequest) Reset() {
	*x = PingDBRequest{}
	mi := &file_proto_grpcserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDBRequest) ProtoMessage() {}

func (x *PingDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDBRequest.ProtoReflect.Descriptor instead.
func (*PingDBRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{3}
}

type PingDBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingDBResponse) Reset() {
	*x = PingDBResponse{}
	mi := &file_proto_grpcserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDBResponse) ProtoMessage() {}

func (x *PingDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDBResponse.ProtoReflect.Descriptor instead.
func (*PingDBResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{4}
}

func (x *PingDBResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         int32                  `protobuf:"varint,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_grpcserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetToken() int32 {
	if x != nil {
		return x.Token
	}
	return 0
}

type ShortenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *Link                  `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenRequest) Reset() {
	*x = ShortenRequest{}
	mi := &file_proto_grpcserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequest) ProtoMessage() {}

func (x *ShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRequest.ProtoReflect.Descriptor instead.
func (*ShortenRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{6}
}

func (x *ShortenRequest) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

func (x *ShortenRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ShortenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shortlink     *ShortLink             `protobuf:"bytes,1,opt,name=shortlink,proto3" json:"shortlink,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenResponse) Reset() {
	*x = ShortenResponse{}
	mi := &file_proto_grpcserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResponse) ProtoMessage() {}

func (x *ShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenResponse.ProtoReflect.Descriptor instead.
func (*ShortenResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{7}
}

func (x *ShortenResponse) GetShortlink() *ShortLink {
	if x != nil {
		return x.Shortlink
	}
	return nil
}

func (x *ShortenResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ShortenResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ShortenJSONRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenJSONRequest) Reset() {
	*x = ShortenJSONRequest{}
	mi := &file_proto_grpcserver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenJSONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenJSONRequest) ProtoMessage() {}

func (x *ShortenJSONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenJSONRequest.ProtoReflect.Descriptor instead.
func (*ShortenJSONRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{8}
}

func (x *ShortenJSONRequest) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *ShortenJSONRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ShortenJSONResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenJSONResponse) Reset() {
	*x = ShortenJSONResponse{}
	mi := &file_proto_grpcserver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenJSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenJSONResponse) ProtoMessage() {}

func (x *ShortenJSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenJSONResponse.ProtoReflect.Descriptor instead.
func (*ShortenJSONResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{9}
}

func (x *ShortenJSONResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *ShortenJSONResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ShortenJSONResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ShortenBatchJSONRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchJSONRequest) Reset() {
	*x = ShortenBatchJSONRequest{}
	mi := &file_proto_grpcserver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchJSONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchJSONRequest) ProtoMessage() {}

func (x *ShortenBatchJSONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchJSONRequest.ProtoReflect.Descriptor instead.
func (*ShortenBatchJSONRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{10}
}

func (x *ShortenBatchJSONRequest) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *ShortenBatchJSONRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ShortenBatchJSONResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchJSONResponse) Reset() {
	*x = ShortenBatchJSONResponse{}
	mi := &file_proto_grpcserver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchJSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchJSONResponse) ProtoMessage() {}

func (x *ShortenBatchJSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchJSONResponse.ProtoReflect.Descriptor instead.
func (*ShortenBatchJSONResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{11}
}

func (x *ShortenBatchJSONResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *ShortenBatchJSONResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ShortenBatchJSONResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ExpandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shortlink     *ShortLink             `protobuf:"bytes,1,opt,name=shortlink,proto3" json:"shortlink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandRequest) Reset() {
	*x = ExpandRequest{}
	mi := &file_proto_grpcserver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandRequest) ProtoMessage() {}

func (x *ExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandRequest.ProtoReflect.Descriptor instead.
func (*ExpandRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{12}
}

func (x *ExpandRequest) GetShortlink() *ShortLink {
	if x != nil {
		return x.Shortlink
	}
	return nil
}

type ExpandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *Link                  `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandResponse) Reset() {
	*x = ExpandResponse{}
	mi := &file_proto_grpcserver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandResponse) ProtoMessage() {}

func (x *ExpandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandResponse.ProtoReflect.Descriptor instead.
func (*ExpandResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{13}
}

func (x *ExpandResponse) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

func (x *ExpandResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ExpandResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ExpandUserURLSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandUserURLSRequest) Reset() {
	*x = ExpandUserURLSRequest{}
	mi := &file_proto_grpcserver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandUserURLSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandUserURLSRequest) ProtoMessage() {}

func (x *ExpandUserURLSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandUserURLSRequest.ProtoReflect.Descriptor instead.
func (*ExpandUserURLSRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{14}
}

func (x *ExpandUserURLSRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ExpandUserURLSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandUserURLSResponse) Reset() {
	*x = ExpandUserURLSResponse{}
	mi := &file_proto_grpcserver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandUserURLSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandUserURLSResponse) ProtoMessage() {}

func (x *ExpandUserURLSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandUserURLSResponse.ProtoReflect.Descriptor instead.
func (*ExpandUserURLSResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{15}
}

func (x *ExpandUserURLSResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *ExpandUserURLSResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type DeleteUserURLSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Json          string                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLSRequest) Reset() {
	*x = DeleteUserURLSRequest{}
	mi := &file_proto_grpcserver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLSRequest) ProtoMessage() {}

func (x *DeleteUserURLSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLSRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserURLSRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteUserURLSRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *DeleteUserURLSRequest) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type DeleteUserURLSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLSResponse) Reset() {
	*x = DeleteUserURLSResponse{}
	mi := &file_proto_grpcserver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLSResponse) ProtoMessage() {}

func (x *DeleteUserURLSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLSResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserURLSResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteUserURLSResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetServerStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerStatsRequest) Reset() {
	*x = GetServerStatsRequest{}
	mi := &file_proto_grpcserver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStatsRequest) ProtoMessage() {}

func (x *GetServerStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStatsRequest.ProtoReflect.Descriptor instead.
func (*GetServerStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{18}
}

type GetServerStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerStatsResponse) Reset() {
	*x = GetServerStatsResponse{}
	mi := &file_proto_grpcserver_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStatsResponse) ProtoMessage() {}

func (x *GetServerStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpcserver_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStatsResponse.ProtoReflect.Descriptor instead.
func (*GetServerStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpcserver_proto_rawDescGZIP(), []int{19}
}

func (x *GetServerStatsResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *GetServerStatsResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_proto_grpcserver_proto protoreflect.FileDescriptor

const file_proto_grpcserver_proto_rawDesc = "" +
	"\n" +
	"\x16proto/grpcserver.proto\x12\n" +
	"grpcserver\"\x18\n" +
	"\x04Link\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\")\n" +
	"\tShortLink\x12\x1c\n" +
	"\tshortlink\x18\x01 \x01(\tR\tshortlink\" \n" +
	"\x06Status\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"\x0f\n" +
	"\rPingDBRequest\"<\n" +
	"\x0ePingDBResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.grpcserver.StatusR\x06status\"\x1c\n" +
	"\x04User\x12\x14\n" +
	"\x05token\x18\x01 \x01(\x05R\x05token\"\\\n" +
	"\x0eShortenRequest\x12$\n" +
	"\x04link\x18\x01 \x01(\v2\x10.grpcserver.LinkR\x04link\x12$\n" +
	"\x04user\x18\x02 \x01(\v2\x10.grpcserver.UserR\x04user\"\x98\x01\n" +
	"\x0fShortenResponse\x123\n" +
	"\tshortlink\x18\x01 \x01(\v2\x15.grpcserver.ShortLinkR\tshortlink\x12*\n" +
	"\x06status\x18\x02 \x01(\v2\x12.grpcserver.StatusR\x06status\x12$\n" +
	"\x04user\x18\x03 \x01(\v2\x10.grpcserver.UserR\x04user\"N\n" +
	"\x12ShortenJSONRequest\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\x12$\n" +
	"\x04user\x18\x02 \x01(\v2\x10.grpcserver.UserR\x04user\"{\n" +
	"\x13ShortenJSONResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\x12*\n" +
	"\x06status\x18\x02 \x01(\v2\x12.grpcserver.StatusR\x06status\x12$\n" +
	"\x04user\x18\x03 \x01(\v2\x10.grpcserver.UserR\x04user\"S\n" +
	"\x17ShortenBatchJSONRequest\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\x12$\n" +
	"\x04user\x18\x02 \x01(\v2\x10.grpcserver.UserR\x04user\"\x80\x01\n" +
	"\x18ShortenBatchJSONResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\x12*\n" +
	"\x06status\x18\x02 \x01(\v2\x12.grpcserver.StatusR\x06status\x12$\n" +
	"\x04user\x18\x03 \x01(\v2\x10.grpcserver.UserR\x04user\"D\n" +
	"\rExpandRequest\x123\n" +
	"\tshortlink\x18\x01 \x01(\v2\x15.grpcserver.ShortLinkR\tshortlink\"\x88\x01\n" +
	"\x0eExpandResponse\x12$\n" +
	"\x04link\x18\x01 \x01(\v2\x10.grpcserver.LinkR\x04link\x12*\n" +
	"\x06status\x18\x02 \x01(\v2\x12.grpcserver.StatusR\x06status\x12$\n" +
	"\x04user\x18\x03 \x01(\v2\x10.grpcserver.UserR\x04user\"=\n" +
	"\x15ExpandUserURLSRequest\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.grpcserver.UserR\x04user\"X\n" +
	"\x16ExpandUserURLSResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\x12*\n" +
	"\x06status\x18\x02 \x01(\v2\x12.grpcserver.StatusR\x06status\"Q\n" +
	"\x15DeleteUserURLSRequest\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.grpcserver.UserR\x04user\x12\x12\n" +
	"\x04json\x18\x02 \x01(\tR\x04json\"D\n" +
	"\x16DeleteUserURLSResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.grpcserver.StatusR\x06status\"\x17\n" +
	"\x15GetServerStatsRequest\"X\n" +
	"\x16GetServerStatsResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\x12*\n" +
	"\x06status\x18\x02 \x01(\v2\x12.grpcserver.StatusR\x06status2\x8a\x05\n" +
	"\bShortUrl\x12?\n" +
	"\x06PingDB\x12\x19.grpcserver.PingDBRequest\x1a\x1a.grpcserver.PingDBResponse\x12B\n" +
	"\aShorten\x12\x1a.grpcserver.ShortenRequest\x1a\x1b.grpcserver.ShortenResponse\x12N\n" +
	"\vShortenJSON\x12\x1e.grpcserver.ShortenJSONRequest\x1a\x1f.grpcserver.ShortenJSONResponse\x12]\n" +
	"\x10ShortenBatchJSON\x12#.grpcserver.ShortenBatchJSONRequest\x1a$.grpcserver.ShortenBatchJSONResponse\x12?\n" +
	"\x06Expand\x12\x19.grpcserver.ExpandRequest\x1a\x1a.grpcserver.ExpandResponse\x12W\n" +
	"\x0eExpandUserURLS\x12!.grpcserver.ExpandUserURLSRequest\x1a\".grpcserver.ExpandUserURLSResponse\x12W\n" +
	"\x0eDeleteUserURLS\x12!.grpcserver.DeleteUserURLSRequest\x1a\".grpcserver.DeleteUserURLSResponse\x12W\n" +
	"\x0eGetServerStats\x12!.grpcserver.GetServerStatsRequest\x1a\".grpcserver.GetServerStatsResponseB\fZ\n" +
	"grpc/protob\x06proto3"

var (
	file_proto_grpcserver_proto_rawDescOnce sync.Once
	file_proto_grpcserver_proto_rawDescData []byte
)

func file_proto_grpcserver_proto_rawDescGZIP() []byte {
	file_proto_grpcserver_proto_rawDescOnce.Do(func() {
		file_proto_grpcserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grpcserver_proto_rawDesc), len(file_proto_grpcserver_proto_rawDesc)))
	})
	return file_proto_grpcserver_proto_rawDescData
}

var file_proto_grpcserver_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_grpcserver_proto_goTypes = []any{
	(*Link)(nil),                     // 0: grpcserver.Link
	(*ShortLink)(nil),                // 1: grpcserver.ShortLink
	(*Status)(nil),                   // 2: grpcserver.Status
	(*PingDBRequest)(nil),            // 3: grpcserver.PingDBRequest
	(*PingDBResponse)(nil),           // 4: grpcserver.PingDBResponse
	(*User)(nil),                     // 5: grpcserver.User
	(*ShortenRequest)(nil),           // 6: grpcserver.ShortenRequest
	(*ShortenResponse)(nil),          // 7: grpcserver.ShortenResponse
	(*ShortenJSONRequest)(nil),       // 8: grpcserver.ShortenJSONRequest
	(*ShortenJSONResponse)(nil),      // 9: grpcserver.ShortenJSONResponse
	(*ShortenBatchJSONRequest)(nil),  // 10: grpcserver.ShortenBatchJSONRequest
	(*ShortenBatchJSONResponse)(nil), // 11: grpcserver.ShortenBatchJSONResponse
	(*ExpandRequest)(nil),            // 12: grpcserver.ExpandRequest
	(*ExpandResponse)(nil),           // 13: grpcserver.ExpandResponse
	(*ExpandUserURLSRequest)(nil),    // 14: grpcserver.ExpandUserURLSRequest
	(*ExpandUserURLSResponse)(nil),   // 15: grpcserver.ExpandUserURLSResponse
	(*DeleteUserURLSRequest)(nil),    // 16: grpcserver.DeleteUserURLSRequest
	(*DeleteUserURLSResponse)(nil),   // 17: grpcserver.DeleteUserURLSResponse
	(*GetServerStatsRequest)(nil),    // 18: grpcserver.GetServerStatsRequest
	(*GetServerStatsResponse)(nil),   // 19: grpcserver.GetServerStatsResponse
}
var file_proto_grpcserver_proto_depIdxs = []int32{
	2,  // 0: grpcserver.PingDBResponse.status:type_name -> grpcserver.Status
	0,  // 1: grpcserver.ShortenRequest.link:type_name -> grpcserver.Link
	5,  // 2: grpcserver.ShortenRequest.user:type_name -> grpcserver.User
	1,  // 3: grpcserver.ShortenResponse.shortlink:type_name -> grpcserver.ShortLink
	2,  // 4: grpcserver.ShortenResponse.status:type_name -> grpcserver.Status
	5,  // 5: grpcserver.ShortenResponse.user:type_name -> grpcserver.User
	5,  // 6: grpcserver.ShortenJSONRequest.user:type_name -> grpcserver.User
	2,  // 7: grpcserver.ShortenJSONResponse.status:type_name -> grpcserver.Status
	5,  // 8: grpcserver.ShortenJSONResponse.user:type_name -> grpcserver.User
	5,  // 9: grpcserver.ShortenBatchJSONRequest.user:type_name -> grpcserver.User
	2,  // 10: grpcserver.ShortenBatchJSONResponse.status:type_name -> grpcserver.Status
	5,  // 11: grpcserver.ShortenBatchJSONResponse.user:type_name -> grpcserver.User
	1,  // 12: grpcserver.ExpandRequest.shortlink:type_name -> grpcserver.ShortLink
	0,  // 13: grpcserver.ExpandResponse.link:type_name -> grpcserver.Link
	2,  // 14: grpcserver.ExpandResponse.status:type_name -> grpcserver.Status
	5,  // 15: grpcserver.ExpandResponse.user:type_name -> grpcserver.User
	5,  // 16: grpcserver.ExpandUserURLSRequest.user:type_name -> grpcserver.User
	2,  // 17: grpcserver.ExpandUserURLSResponse.status:type_name -> grpcserver.Status
	5,  // 18: grpcserver.DeleteUserURLSRequest.user:type_name -> grpcserver.User
	2,  // 19: grpcserver.DeleteUserURLSResponse.status:type_name -> grpcserver.Status
	2,  // 20: grpcserver.GetServerStatsResponse.status:type_name -> grpcserver.Status
	3,  // 21: grpcserver.ShortUrl.PingDB:input_type -> grpcserver.PingDBRequest
	6,  // 22: grpcserver.ShortUrl.Shorten:input_type -> grpcserver.ShortenRequest
	8,  // 23: grpcserver.ShortUrl.ShortenJSON:input_type -> grpcserver.ShortenJSONRequest
	10, // 24: grpcserver.ShortUrl.ShortenBatchJSON:input_type -> grpcserver.ShortenBatchJSONRequest
	12, // 25: grpcserver.ShortUrl.Expand:input_type -> grpcserver.ExpandRequest
	14, // 26: grpcserver.ShortUrl.ExpandUserURLS:input_type -> grpcserver.ExpandUserURLSRequest
	16, // 27: grpcserver.ShortUrl.DeleteUserURLS:input_type -> grpcserver.DeleteUserURLSRequest
	18, // 28: grpcserver.ShortUrl.GetServerStats:input_type -> grpcserver.GetServerStatsRequest
	4,  // 29: grpcserver.ShortUrl.PingDB:output_type -> grpcserver.PingDBResponse
	7,  // 30: grpcserver.ShortUrl.Shorten:output_type -> grpcserver.ShortenResponse
	9,  // 31: grpcserver.ShortUrl.ShortenJSON:output_type -> grpcserver.ShortenJSONResponse
	11, // 32: grpcserver.ShortUrl.ShortenBatchJSON:output_type -> grpcserver.ShortenBatchJSONResponse
	13, // 33: grpcserver.ShortUrl.Expand:output_type -> grpcserver.ExpandResponse
	15, // 34: grpcserver.ShortUrl.ExpandUserURLS:output_type -> grpcserver.ExpandUserURLSResponse
	17, // 35: grpcserver.ShortUrl.DeleteUserURLS:output_type -> grpcserver.DeleteUserURLSResponse
	19, // 36: grpcserver.ShortUrl.GetServerStats:output_type -> grpcserver.GetServerStatsResponse
	29, // [29:37] is the sub-list for method output_type
	21, // [21:29] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proto_grpcserver_proto_init() }
func file_proto_grpcserver_proto_init() {
	if File_proto_grpcserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grpcserver_proto_rawDesc), len(file_proto_grpcserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grpcserver_proto_goTypes,
		DependencyIndexes: file_proto_grpcserver_proto_depIdxs,
		MessageInfos:      file_proto_grpcserver_proto_msgTypes,
	}.Build()
	File_proto_grpcserver_proto = out.File
	file_proto_grpcserver_proto_goTypes = nil
	file_proto_grpcserver_proto_depIdxs = nil
}
